import './globals.css'
import RootStyleRegistry from '@/libs/emotion'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><RootStyleRegistry>{children}</RootStyleRegistry></body>
    </html>
  )
}
